### ISSUE TITLE
Tabbar can not change

### ISSUE THREAD

**Issue by VineFiner** [microsoft/FluentDarkModeKit#86] opened 2020-07-10 02:00 UTC
Click on the second item and refresh the theme. The bottom tabbar will not change.

**Comment by levinli303** [comment] 2020-07-10 03:02
This sounds like a bug in UIKit. I managed to reproduce with a project without FluentDarkModeKit. The setup is like this:

1. Window's root view controller is set to UITabBarController with a UINavigationController embedded, the UINavigationController embeds another UIViewController.
2. The UIViewController's background color is set to a non dynamic color.

Changing the window's overrideUserInterfaceStyle does not change the tabbar background.

**Comment by levinli303** [comment] 2020-07-10 03:49
Closing since it is not a bug in FluentDarkModeKit

**Closed by levinli303** 2020-07-10 03:49 UTC
